name: Bump Version

on:
  repository_dispatch:
    types:
    - zitadel-released

jobs:
  bump:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: write
    steps:
    - id: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Bump ZITADEL Version
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'charts/zitadel/Chart.yaml'
        propertyPath: 'appVersion'
        value: ${{ github.event.client_payload.semanticoutputs.new_release_version }}
        commitChange: false
        createPR: false

    - name: Read Current Chart Version
      id: current-chart-version
      uses: jbutcher5/read-yaml@1.6
      with:
        file: './charts/zitadel/Chart.yaml'
        key-path: '["version"]'

    - name: Read Current ZITADEL Version
      id: current-zitadel-version
      uses: jbutcher5/read-yaml@1.6
      with:
        file: './charts/zitadel/Chart.yaml'
        key-path: '["appVersion"]'

    - name: Print Current Versions
      run: |
        echo "Chart Version Outputs: ${{ steps.current-chart-version.outputs }}"
        echo "Chart Version Data: ${{ steps.current-chart-version.outputs.data }}"
        echo "Chart Version: ${{ steps.current-chart-version.outputs.data.version }}"
        echo "ZITADEL Version Outputs: ${{ steps.current-zitadel-version.outputs }}"
        echo "ZITADEL Version Data: ${{ steps.current-zitadel-version.outputs.data }}"
        echo "ZITADEL Version: ${{ steps.current-zitadel-version.outputs.data.appVersion }}"

    - name: Parse Last ZITADEL Version
      id: parsed-last-zitadel-version
      uses: booxmedialtd/ws-action-parse-semver@v1
      with:
        input_string: ${{ steps.current-zitadel-version.outputs.data.appVersion }}

    - name: Set Version Type
      id: set-version-type
      run: |
        [ ${{ github.event.client_payload.semanticoutputs.new_release_patch_version }} -gt  ${{ steps.parsed-last-zitadel-version.outputs.patch }}] && echo '::set-output name=type::PATCH'
        [ ${{ github.event.client_payload.semanticoutputs.new_release_minor_version }} -gt  ${{ steps.parsed-last-zitadel-version.outputs.minor }}] && echo '::set-output name=type::MINOR'
        [ ${{ github.event.client_payload.semanticoutputs.new_release_major_version }} -gt  ${{ steps.parsed-last-zitadel-version.outputs.major }}] && echo '::set-output name=type::MAJOR'

    - name: Bump Chart Version
      id: bumped-chart-version
      uses: ./
      with:
        semantic-version: ${{ steps.current-chart-version.outputs.data.version }}
        version-type: ${{ steps.set-version-type.outputs.type }}

    - name: Update Chart Version
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'charts/zitadel/Chart.yaml'
        propertyPath: 'version'
        value: ${{ steps.bumped-chart-version.outputs.bumped-semantic-version }}
        commmitChange: false
        createPR: false

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: Bump ZITADEL Version
        branch: create-pull-request/bump
        delete-branch: true
